---
- name: user module demo
  hosts: kube-cluster
  become: true
  vars:
    user: "ansible"
    password: "1"
    group: "wheel"

  tasks:
    - name: change password
      ansible.builtin.user:
        name: "{{ user }}"
        group: "{{ group }}"
        state: present
        password: "{{ password | password_hash('sha512') }}"
