---
- hosts:  all
  become: true
  become_user: root
  vars_files:
    - secret.yml
  tasks:
    - name: Criando Usuário
      user:
        name: "{{ username }}"
        password: "{{ hwpass }}"
        state: present