---
- hosts: kube-cluster
  become: true
  tasks:
    - name: Atualizando pacotes
      yum:
        name: '*'
        state: latest

    - name: instalando pacote ( python 3 )
      yum:
          name: ['python3']
          state: present