---
- hosts: kube-cluster
  become: true
  tasks:
    - name: Atualizando pacotes
      yum:
        name: '*'
        state: latest

    - name: instalando pacote ( python 3 | java-1.8.0-OpenJDK | cockpit)
      yum:
          name: ['python3', 'java-1.8.0-openjdk', 'cockpit', 'cockpit-storaged']
          state: present

    - name: Iniciando Serviço Cockpit
      service:
          name: cockpit
          state: started
          enabled: true

    - name: Verificando porta 9090 aberta
      shell: |
          ss -na | grep 9090
