---
- hosts: kube-cluster
  become: true
  tasks:
    - name: Atualizando pacotes
      yum:
        name: '*'
        state: latest

    - name: instalando pacote ( python 3 | java-1.8.0-OpenJDK )
      yum:
          name: ['python3', 'java-1.8.0-openjdk']
          state: present
