---
- name: Create directory
  hosts: all
  become: true
  tasks:
    - name: Montando NFS volume
      ansible.posix.mount:
        src: 192.168.0.24:/
        path: /mnt
        opts: 
        - rw
        - sync
        - hard
        - intr
        state: mounted
        fstype: nfs
    - name: criando diretórios
      ansible.builtin.file:
        path: "{{ item }}"
        mode: "1777"
        state: directory
      loop:
        - /mysql
        - /jenkins
        - /prometheus/server
        - /prometheus/alertmanager
        - /zabbix
        - /zabbix/zabbix-frontend
        - /zabbix/zabbix-server
        - /zabbix/zabbix-PostgreSQL
        - /zabbix/zabbix-MySQL
        - /MySQL
        - /wazuh
        - /PostgreSQL
        - /elastic-stack/elasticsearch-master-0
        - /elastic-stack/elasticsearch-master-1
        - /elastic-stack/elasticsearch-master-2
    - name: Desmontando volume
      ansible.posix.mount:
        path: /mnt
        state: unmounted
