---
- name: Update packages
  hosts: all
  become: yes
  become_user: ansible
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
        update_cache: yes
        update_only: yes
      register: yum_update_status

    - name: Remove packates not needed anymore
      yum:
        autoremove: yes
